### ISSUE TITLE
Tree View right-click context menu for Document cut off instead of expanding to fit all options

### ISSUE THREAD

**Issue by brandonbeaumia** [dracula/freecad#13]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Most context menus are fine, but it seems the one that are missing any keyboard shortcuts are most likely to have issues?

![image](https://user-images.githubusercontent.com/650565/217887500-23d6550a-0307-44a0-86ba-0dd2a447fe88.png)

**Comment by Chrismettal** [comment]
![image](https://user-images.githubusercontent.com/39636046/227725404-209eb190-5233-4aa2-80aa-dd77db1d37ca.png)

This one I am unable to reproduce after merging your other commits.. Which version of FreeCAD are you running?

```
OS: KDE Flatpak runtime (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.6, Qt 5.15.8, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * FreeCAD-Desktop-Preference-Pack 0.0.1
  * Behave-Dark-Colors 0.1.1
  * LocalDracula 0.0.2
```

**Comment by brandonbeaumia** [comment]
Was this tested after adding the 10px padding from #14?

I did do a lot of faffing about with context menus for #27 and may have inadvertently fixed this problem as well. I'll reopen if I find the issue somewhere else; thanks for checking in on this after the merges!

**Comment by Chrismettal** [comment]
I tested it before the padding was added so that shouldn't be the reason it's fixed now. In any case, glad to hear it works for you know and let's reopen if it reappears!
