### ISSUE TITLE
Tree View right-click context menu (no selection; right-click on "Application" line) submenu arrows overlap text

### ISSUE THREAD

**Issue by brandonbeaumia** [dracula/freecad#14]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Possibly related to #13. Seems like any context menu with a keyboard shortcut listed looks fine, but without any shortcuts things get a little wonky due to small size?

![image](https://user-images.githubusercontent.com/650565/217888775-f7c08348-e792-4040-b363-aca695f42e24.png)

**Comment by Chrismettal** [comment]
This seems to happen in all stylesheets that I tested.
Also happens in ALL cases where a dropdown shows a right arrow for any reason, as it will always be at the position where the longest word in that dropdown will end.

Fixed by adding 10px more padding to the right (The size of the arrow)

**Comment by Chrismettal** [comment]
Good morning @luzpaz,

is there a tracking ticket for FreeCAD already for stuff that applies to all stylesheets? I feel like a lot of things get fixed on an individual stylesheet level but never really transferred to others, especially the bundled ones which all show this behavior.

**Comment by luzpaz** [comment]
@Chrismettal kind of clunky but checkout https://github.com/FreeCAD/FreeCAD-addons/issues/201
