### ISSUE TITLE
Spreadsheet: no indication that Content or Alias fields are editable (especially when no text is present)

### ISSUE THREAD

**Issue by brandonbeaumia** [dracula/freecad#15]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Possibly a conscious design decision here, but it did throw me off a little bit (and I think this makes the Alias function much less discoverable).

![image](https://user-images.githubusercontent.com/650565/217893797-e1b7aa61-f187-4ad1-a5c9-ce27f333cedc.png)

**Comment by Chrismettal** [comment]
This one goes very deep and is not only a problem with these specific text boxes.
Most forms of controls use the same color as the background in most scenarios. Look at this comparison for example:

## Existing Stylesheet:

![image](https://user-images.githubusercontent.com/39636046/227725016-a305c37e-502b-48ba-991b-e36b39261928.png)

![image](https://user-images.githubusercontent.com/39636046/227725035-6dce906f-ec28-4a09-bac4-0a8f361fda15.png)


## Modified to use #282a36 for the background on controls:

![image](https://user-images.githubusercontent.com/39636046/227725101-1042ab30-8ca8-470d-8d1c-fb5dfb636069.png)

![image](https://user-images.githubusercontent.com/39636046/227725106-028f6957-30b8-4f1c-baeb-438ce6809073.png)

This is with the following line changed:

![image](https://user-images.githubusercontent.com/39636046/227725165-d0ff13b1-9a14-4eaa-b2f5-5d943aac8f34.png)

In my opinion this single change benefits readability on basically all controls, though I am unsure of the exact color to use.

@brandonbeaumia, @tim-clifford, what are your thoughts on the colors used in the second set of screenshots? While a little low contrast I feel like the controls are very easy on the eyes that way. Don't think an actual "color" should get involved here, but do you think the text color being gray as well is sufficient or should we crank the contrast to a darker font color?

I intentionally didn't add a border as I think a third hue getting involved might be a bit much.

**Comment by brandonbeaumia** [comment]
Hm. I think aesthetically the contrast would be fine, but if you have multiple controls in a row as shown in this SS, it makes the drop-downs look inactive because I'm expecting the same text color for any active controls.

![image](https://user-images.githubusercontent.com/650565/227726750-5f9ea760-526e-4bec-90c8-cff11689980c.png)

You'd end up with the same values as the preference pack table view right above this, which works pretty well with the lighter font in my opinion. Not quite as easy on the eyes, but more consistent with the rest of the theme?

**Comment by Chrismettal** [comment]
![image](https://user-images.githubusercontent.com/39636046/227728585-28c77475-8ee5-4752-9835-846c5e0b345c.png)

Agreed. Didn't occur to me that the low contrast would suggest an inactive control.
