### ISSUE TITLE
Spreadsheet: no pre-selection highlighting of columns/rows

### ISSUE THREAD

**Issue by brandonbeaumia** [dracula/freecad#16]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

FreeCAD Classic:

https://user-images.githubusercontent.com/650565/217899723-f3659dd3-4fb6-4c3a-b0df-c4e18fc149d3.mp4

Dracula:

https://user-images.githubusercontent.com/650565/217899816-8a38b474-c37c-494b-a62a-fcfa0655d93e.mp4

**Comment by Chrismettal** [comment]
Thanks! I just added a `QHeaderView::section:hover` color to the spreadsheet.
