### ISSUE TITLE
Turn this in the a FreeCAD Preference Pack

### ISSUE THREAD

**Issue by luzpaz** [dracula/freecad#2]
See https://github.com/Chrismettal/FreeCAD-Behave-Dark-Preference-Pack  

Edit: FreeCAD-Behave was added to the Addon Manager (see https://github.com/FreeCAD/FreeCAD-addons/commit/0d23295401db40d413abf45818e6800c287868e0)

ref: https://github.com/FreeCAD/FreeCAD-addons/issues/201

**Comment by tim-clifford** [comment]
Hi @luzpaz, if you want to make this change I'd be happy to review a PR. Unfortunately I don't have the time to work on it right now.

**Comment by luzpaz** [comment]
Possibly. Can you add a 'Help Wanted' to this ticket JIC anyone else is inspired ?

**Comment by Chrismettal** [comment]
To turn this into a preference pack, don't we need to first include this stylesheet into FreeCADs source @luzpaz ?

If the stylesheet was packaged into FreeCAD I would like to wrap it into a Preference Pack, but I don't know what the current consensus is regarding getting "every" stylesheet into the FreeCAD source.

**Comment by Chrismettal** [comment]
That's how it worked for the Behave theme at least. The Preference pack chooses the already included stylesheet and sets all the colors not already set by the sheet.

I'm not sure if a preference pack alone is able to set all colors that the stylesheet usually sets.

**Comment by Chrismettal** [comment]
I have opened up PRs to refactor this repo into a PreferencePack, as well as distribute it with the internal addon manager.

You can try it out without merging by adding [my fork](https://github.com/Chrismettal/FreeCAD-Dracula-Preference-Pack) to your FreeCADs addon manager custom repo list like this:

![image](https://user-images.githubusercontent.com/39636046/178148522-ecba5c42-b832-429b-8eef-0db0603b06ce.png)

Searching for preference packs via the addon manager and installing the fork:

![image](https://user-images.githubusercontent.com/39636046/178148602-5594ce87-27c9-4253-8f3d-87d8a75a2263.png)

And lastly applying it from within preferences:

![image](https://user-images.githubusercontent.com/39636046/178148624-96e526e6-3f90-4576-927f-9d5f36b51f4a.png)

**Comment by tim-clifford** [comment]
closed by #3
