### ISSUE TITLE
Inconsistent highlight widths in TreeView

### ISSUE THREAD

**Issue by brandonbeaumia** [dracula/freecad#25]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

![inconsistent highlight widths](https://user-images.githubusercontent.com/650565/218343089-75e7fc23-e64c-4650-b71a-2136ad2ac128.png)

**Comment by Chrismettal** [comment]
In my opinion the full width selection wouldn't be that big of a deal, if you could even see which column is actually selected right now. You notice in basically all themes of FreeCAD, that you need to "right arrow" twice to open up an item, but you never see the selection actually move from the "Labels" column to the "Description" one.

As far as I am aware however, this behavior can't currently be changed by PreferencePacks. Gotta admit tho, I am not currently on top of all the changes happening around FreeCAD themeing.
