### ISSUE TITLE
remove blank space after the icons in the menu

### ISSUE THREAD

**Issue by MisterMakerNL** [dracula/freecad#4]
In almost every black theme there is this bug, in the stylesheet it's called a fix for something but once you remove the fix, nothing breaks.

![20220710_225430](https://user-images.githubusercontent.com/29804962/178161808-5a86a609-35c2-49de-b5bf-0616efa864b4.jpg)

**Comment by MisterMakerNL** [comment]
Wow nice work! 
Instead of a colored border could be make it look like a pressed in button?

**Comment by Chrismettal** [comment]
That looks quite good! And matches QTs intention.

Gonna test on Linux later and implement your fix for the other stylesheets sitting in the FreeCAD source, using a fitting "checked" color for each stylesheet individually, unless you're already on it?

**Comment by tim-clifford** [comment]
This is great, can we get a PR? I'd do it myself but I'm a bit short on time nowadays

**Comment by Chrismettal** [comment]
Sure thing!

**Comment by MisterMakerNL** [comment]
Nice, I am happy it also worked in Linux!

**Comment by tim-clifford** [comment]
closed by #6
