### ISSUE TITLE
Update install instructions on https://draculatheme.com/freecad page

### ISSUE THREAD

**Issue by luzpaz** [dracula/freecad#8]
Currently: ![Screenshot_20220714_161020](https://user-images.githubusercontent.com/4140247/179074393-2e574e20-a86f-4ed8-8dd0-84639a57594a.png)

After Preference pack it's possible to use the addon manager to seamlessly install Dracula theme.

**Comment by tim-clifford** [comment]
the website will automatically update to reflect `INSTALL.md` when it's next regenerated, which should be relatively soon.
